import "server-only";

// Generated by scripts/generate_challenges.py. Do not edit by hand.
export const adminUsername = "administrator";
export const adminPasswordSalt = "d621a9b17a0d2c4ec4eda9cedcd6ef7a";
export const adminPasswordHash = "7a01a4a3a2e55fdaaf633eafde887eee068aa66af20df65b30ee6d6982fd5357";
export const adminSessionSigningKey = "043b478a99e58508b0f6a438131b352631b305f4dff9869cb6f4cfd49f89bc51";
export const completionSigningKey = "62a7c0a6371958a2d1f898f0def4aabb6aedcdce8c0e2715e2000ddff7837449";
export const pwnIssuerSecret = "7bbbd87b98ea9e4d58cafeae6a6a38f1c4802ca93d3e20da106a4df3b3cc363b";
export const finalChallengeFlag = "FLAG{CITADELLE_CYBERSEC_CHALLENGE_TECHSPARK_ORA_CAM2_2026}";
