import "server-only";

// Generated by scripts/generate_challenges.py. Do not edit by hand.
export const protectedSupportNote = "FLAG{HELP_ASSISTANT_BYPASSED}\n\nInternal case HC-204: Inspect the regional locations page source. The useful values are split across an office ledger, an archive note, and retired display preferences.\n\nNext destination: Citadelle locations.";
