import "server-only";

// Generated by scripts/generate_challenges.py. Do not edit by hand.
export const adminUsername = "administrator";
export const adminPasswordSalt = "d621a9b17a0d2c4ec4eda9cedcd6ef7a";
export const adminPasswordHash = "7a01a4a3a2e55fdaaf633eafde887eee068aa66af20df65b30ee6d6982fd5357";
export const adminSessionSigningKey = "043b478a99e58508b0f6a438131b352631b305f4dff9869cb6f4cfd49f89bc51";
