import "server-only";

// Generated by scripts/generate_challenges.py. Do not edit by hand.
export const protectedSupportNote = "I protect a network by monitoring and controlling incoming and outgoing traffic.";
export const chatbotUsername = "administrator";
