import "server-only";

// Generated by scripts/generate_challenges.py. Do not edit by hand.
export const adminUsername = "administrator";
export const adminPasswordSalt = "d621a9b17a0d2c4ec4eda9cedcd6ef7a";
export const adminPasswordHash = "deb3397fb7231276982990ba2dcb7d33f12f8fd517205700d735ae4308440f9d";
export const adminSessionSigningKey = "e66bcc81c147635c51fac1b08d1e662a37c4ea5d57bfcde63756707f863f98fe";
export const completionSigningKey = "62a7c0a6371958a2d1f898f0def4aabb6aedcdce8c0e2715e2000ddff7837449";
export const pwnIssuerSecret = "7bbbd87b98ea9e4d58cafeae6a6a38f1c4802ca93d3e20da106a4df3b3cc363b";
export const finalChallengeFlag = "FLAG{CITADELLE_CYBERSEC_CHALLENGE_TECHSPARK_ORA_CAM2_2026}";
