// Generated by scripts/generate_challenges.py. Do not edit by hand.
export const sourceClueParts = ["SSBhbSBhIHR5cGUgb2YgQUkgdGhhdCBsZWFybnMgZnJvbSBkYXR", "hIHRvIG1ha2UgcHJlZGljdGlvbnMgaW5zdGVhZCBvZiBmb2xsb3", "dpbmcgb25seSBleHBsaWNpdGx5IHByb2dyYW1tZWQgcnVsZXMu"] as const;
export const websiteSourceHint = "I am a type of AI that learns from data to make predictions instead of following only explicitly programmed rules.";
export const trainingPasswordHash = "36207a5455299c1cbb355aca0e74bfa8e08f1ab441d9b82731a50ac9db7e5d3c";
