// Generated by scripts/generate_challenges.py. Do not edit by hand.
export const sourceClueParts = ["SSBhbSBhIHR5cGUgb2YgQUkgdGhhdCBsZWFybnMgcGF0dGVybnMgZnJvbSBleG", "FtcGxlcyBpbnN0ZWFkIG9mIGZvbGxvd2luZyBvbmx5IGV4cGxpY2l0bHkgcHJv", "Z3JhbW1lZCBydWxlcy4KCk5leHQgZXZpZGVuY2U6IFN0ZWdhbm9ncmFwaHk="] as const;
export const websiteSourceHint = "I am a type of AI that learns patterns from examples instead of following only explicitly programmed rules.";
export const trainingPasswordHash = "391d182c01fb79afc11eaf82fbc4e9d5f80fd7068f4937ffbe24aa497ff63d2c";
