// Generated by scripts/generate_challenges.py. Do not edit by hand.
export const sourceClueParts = ["RkxBR3tTT1VSQ0VfQ09ERV9JTlNQRUNURUR9CgpNeSB0aGlyZCB", "pcyB0aGUgYW5zd2VyIHRvIHNpeCBtdWx0aXBsaWVkIGJ5IHNldm", "VuLgoKTmV4dCBmaWxlOiBmcmF1ZF9hbmFseXNpcy5pcHluYg=="] as const;
export const trainingPasswordHash = "391d182c01fb79afc11eaf82fbc4e9d5f80fd7068f4937ffbe24aa497ff63d2c";
