#!/usr/bin/env python3
"""Generate Citadelle's student-facing challenge artifacts from one config."""

from __future__ import annotations

import base64
import hashlib
import json
import random
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "facilitator" / "challenge.env"


def load_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            raise ValueError(f"{path}:{number}: expected KEY=VALUE")
        key, raw_value = line.split("=", 1)
        key = key.strip()
        if not re.fullmatch(r"[A-Z][A-Z0-9_]*", key):
            raise ValueError(f"{path}:{number}: invalid key {key!r}")
        raw_value = raw_value.strip()
        try:
            value = json.loads(raw_value) if raw_value.startswith('"') else raw_value
        except json.JSONDecodeError as error:
            raise ValueError(f"{path}:{number}: invalid quoted value") from error
        values[key] = str(value)
    return values


def require(config: dict[str, str], *keys: str) -> None:
    missing = [key for key in keys if not config.get(key)]
    if missing:
        raise ValueError(f"Missing configuration: {', '.join(missing)}")


def message(config: dict[str, str], prefix: str) -> str:
    return "\n\n".join(
        [config[f"{prefix}_FLAG"], config[f"{prefix}_CHARADE"], config[f"{prefix}_NEXT"]]
    )


def generate_image(config: dict[str, str]) -> Path:
    source = ROOT / config["IMAGE_SOURCE"]
    output = ROOT / config["IMAGE_OUTPUT"]
    output.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, output)
    marker = (
        "\n\n[CITADELLE_TRAINING_EVIDENCE]\n"
        f"{message(config, 'IMAGE')}\n"
        "[END_CITADELLE_TRAINING_EVIDENCE]\n"
    )
    with output.open("ab") as image:
        image.write(marker.encode("utf-8"))
    return output


def generate_dns(config: dict[str, str], rng: random.Random) -> Path:
    encoded = base64.b64encode(message(config, "DNS").encode()).decode()
    fragments = [encoded[index : index + 24] for index in range(0, len(encoded), 24)]
    suspicious = [
        f"2026-07-27T09:{14 + index // 4:02d}:{2 + index * 7:02d}Z 10.20.8.14 TXT "
        f"{index + 1:02d}-{fragment}.{config['DNS_DOMAIN']} NOERROR"
        for index, fragment in enumerate(fragments)
    ]
    rng.shuffle(suspicious)
    noise = [
        "2026-07-27T09:13:50Z 10.20.8.14 A portal.citadelle.local 10.20.2.8",
        "2026-07-27T09:13:53Z 10.20.4.21 AAAA updates.training.local NOERROR",
        "2026-07-27T09:14:05Z 10.20.4.21 A cdn.training.local 192.0.2.18",
        "2026-07-27T09:14:13Z 10.20.3.9 A analytics.training.local 192.0.2.30",
        "2026-07-27T09:14:21Z 10.20.4.21 A mail.citadelle.local 10.20.2.15",
        "2026-07-27T09:14:29Z 10.20.6.42 TXT status.telemetry.training.local NOERROR",
        "2026-07-27T09:14:54Z 10.20.6.42 TXT U29mdHdhcmVVcGRhdGU=.telemetry.training.local NOERROR",
        "2026-07-27T09:15:04Z 10.20.8.14 A gateway.citadelle.local 10.20.1.1",
        "2026-07-27T09:15:22Z 10.20.4.21 A help.citadelle.local 10.20.2.22",
        "2026-07-27T09:15:58Z 10.20.8.14 A portal.citadelle.local 10.20.2.8",
    ]
    rows = noise + suspicious
    rng.shuffle(rows)
    output = ROOT / "public" / "evidence" / "network_capture.log"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        "# CITADELLE SECURITY OPERATIONS — DNS resolver export\n"
        "# Training data. Rows may not be in capture order.\n"
        "# Format: timestamp client record query response\n"
        + "\n".join(rows)
        + "\n",
        encoding="utf-8",
    )
    return output


def generate_website(config: dict[str, str]) -> Path:
    encoded = base64.b64encode(message(config, "WEBSITE").encode()).decode()
    size = (len(encoded) + 2) // 3
    fragments = [encoded[index : index + size] for index in range(0, len(encoded), size)]
    output = ROOT / "lib" / "generated-challenge.ts"
    output.write_text(
        "// Generated by scripts/generate_challenges.py. Do not edit by hand.\n"
        f"export const sourceClueParts = {json.dumps(fragments)} as const;\n"
        f"export const trainingPasswordHash = {json.dumps(hashlib.sha256(config['FINAL_PASSWORD'].encode()).hexdigest())};\n",
        encoding="utf-8",
    )
    return output


def generate_chat_secret(config: dict[str, str]) -> Path:
    output = ROOT / "server" / "generated-chat-secret.ts"
    output.parent.mkdir(parents=True, exist_ok=True)
    protected_note = "\n\n".join(
        [config["CHAT_FLAG"], config["CHAT_SECRET_NOTE"], config["CHAT_NEXT"]]
    )
    output.write_text(
        'import "server-only";\n\n'
        "// Generated by scripts/generate_challenges.py. Do not edit by hand.\n"
        f"export const protectedSupportNote = {json.dumps(protected_note)};\n",
        encoding="utf-8",
    )
    return output


def generate_admin_credentials(config: dict[str, str]) -> Path:
    output = ROOT / "server" / "generated-admin-credentials.ts"
    output.parent.mkdir(parents=True, exist_ok=True)
    salt = hashlib.sha256(
        f"citadelle-admin:{config['GENERATION_SEED']}".encode()
    ).hexdigest()[:32]
    password_hash = hashlib.pbkdf2_hmac(
        "sha256",
        config["FINAL_PASSWORD"].encode(),
        bytes.fromhex(salt),
        210_000,
    ).hex()
    signing_key = hashlib.sha256(
        f"{config['GENERATION_SEED']}:{config['FINAL_PASSWORD']}:session".encode()
    ).hexdigest()
    output.write_text(
        'import "server-only";\n\n'
        "// Generated by scripts/generate_challenges.py. Do not edit by hand.\n"
        f"export const adminUsername = {json.dumps(config['ADMIN_USERNAME'])};\n"
        f"export const adminPasswordSalt = {json.dumps(salt)};\n"
        f"export const adminPasswordHash = {json.dumps(password_hash)};\n"
        f"export const adminSessionSigningKey = {json.dumps(signing_key)};\n",
        encoding="utf-8",
    )
    return output


def notebook_cells(config: dict[str, str], completed: bool) -> list[dict[str, object]]:
    clue_b64 = base64.b64encode(message(config, "NOTEBOOK").encode()).decode()
    records = [
        ["TX-1041", "AC-220", "2026-07-27 08:41",  8200, "GB", 1,  82, "Supplier settlement", 18],
        ["TX-1042", "AC-118", "2026-07-27 08:57", 14950, "AE", 5,  22, "New device — client confirmed travel", 76],
        ["TX-1043", "AC-731", "2026-07-27 09:11", 42000, "RO", 9,   8, "ADMIN-RECOVERY:" + clue_b64, 97],
        ["TX-1044", "AC-304", "2026-07-27 09:18",   127, "GB", 0,  91, "Card purchase", 4],
        ["TX-1045", "AC-515", "2026-07-27 09:23",  3750, "FR", 2,  74, "Investment transfer", 19],
        ["TX-1046", "AC-089", "2026-07-27 09:31",  9100, "US", 0,  95, "Wire — confirmed by client", 6],
        ["TX-1047", "AC-622", "2026-07-27 09:44",  6600, "NG", 7,  31, "Account top-up", 84],
        ["TX-1048", "AC-411", "2026-07-27 09:55",   520, "GB", 0,  88, "Standing order", 11],
    ]

    step1_complete = (
        'watchlist_countries = ["RO", "AE", "NG", "UA"]\n'
        'candidates = df[df["country"].isin(watchlist_countries)]\n'
        'candidates[["transaction_id", "country", "failed_login_count",\n'
        '            "device_trust_score", "ip_risk_score", "transaction_note"]]'
    )
    step1_student = (
        '# Countries flagged by the risk team as elevated-risk jurisdictions.\n'
        '# Fill in the variable name inside isin(___) to apply the watchlist filter.\n'
        'watchlist_countries = ["RO", "AE", "NG", "UA"]\n'
        'candidates = df[df["country"].isin(___)]  # ← fill in the variable name\n'
        'candidates[["transaction_id", "country", "failed_login_count",\n'
        '            "device_trust_score", "ip_risk_score", "transaction_note"]]'
    )

    step2_complete = (
        '# All three thresholds must be satisfied simultaneously.\n'
        'suspicious = candidates[\n'
        '    (candidates["failed_login_count"] >= 8) &\n'
        '    (candidates["device_trust_score"] < 15) &\n'
        '    (candidates["ip_risk_score"] > 90)\n'
        ']\n'
        'suspicious'
    )
    step2_student = (
        '# Apply all three risk thresholds — fill in each numeric value.\n'
        '# Hint: failed logins ≥ 8, device trust < 15, IP risk > 90\n'
        'suspicious = candidates[\n'
        '    (candidates["failed_login_count"] >= ___) &\n'
        '    (candidates["device_trust_score"] < ___) &\n'
        '    (candidates["ip_risk_score"] > ___)\n'
        ']\n'
        'suspicious'
    )

    decode_complete = (
        '# Decode the clue embedded in the suspicious transaction note.\n'
        'note = suspicious.iloc[0]["transaction_note"]\n'
        'encoded = note.split(":", 1)[1]  # text after "ADMIN-RECOVERY:"\n'
        'print(base64.b64decode(encoded).decode())'
    )
    decode_student = (
        '# The note field contains "ADMIN-RECOVERY:" followed by a Base64 string.\n'
        '# Split on ":" and decode the second part.\n'
        'note = suspicious.iloc[0]["transaction_note"]\n'
        'encoded = note.split(":", 1)[1]  # text after "ADMIN-RECOVERY:"\n'
        'print(base64.b64decode(encoded).decode())'
    )

    step1 = step1_complete if completed else step1_student
    step2 = step2_complete if completed else step2_student
    decode = decode_complete if completed else decode_student

    def md(text: str) -> dict[str, object]:
        return {"cell_type": "markdown", "metadata": {}, "source": [line + "\n" for line in text.splitlines()]}

    def code(text: str) -> dict[str, object]:
        return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [line + "\n" for line in text.splitlines()]}

    cols = json.dumps([
        "transaction_id", "account_id", "timestamp", "amount", "country",
        "failed_login_count", "device_trust_score", "transaction_note", "ip_risk_score",
    ])

    return [
        md(
            "# Citadelle Bank — Fraud Analysis\n\n"
            "This notebook was recovered from the compromised data-science workstation.\n"
            "The security team believes the attacker left a trace inside one of the flagged transactions.\n\n"
            "**Your objective:** identify the suspicious transaction and decode the message hidden in its note field.\n\n"
            "| Column | Description |\n"
            "|--------|-------------|\n"
            "| `failed_login_count` | Login failures on the account in the 24 h before the transaction |\n"
            "| `device_trust_score` | 0 – unknown device    100 – trusted managed device |\n"
            "| `ip_risk_score` | 0 – clean IP    100 – known-malicious range |"
        ),
        code("import base64\nimport pandas as pd"),
        code(
            f"columns = {cols}\n"
            f"records = {json.dumps(records)}\n"
            "df = pd.DataFrame(records, columns=columns)\n"
            "df"
        ),
        code(
            '# Quick overview: check how many rows and what types we have.\n'
            'print(f"Shape: {df.shape[0]} transactions, {df.shape[1]} columns\\n")\n'
            'print(df[["transaction_id", "country", "amount",\n'
            '          "failed_login_count", "device_trust_score", "ip_risk_score"]].to_string(index=False))'
        ),
        md(
            "## Step 1 — Filter by risk country\n\n"
            "The risk team has flagged a watchlist of elevated-risk jurisdictions.\n"
            "Start by narrowing the dataset to transactions from these countries only.\n\n"
            "> **Note:** A high country-risk score alone is not proof of malicious activity.\n"
            "> One of the candidates has a legitimate explanation in its note field."
        ),
        code(step1),
        md(
            "## Step 2 — Apply multi-signal risk thresholds\n\n"
            "Multiple weak signals together are much stronger evidence than any single indicator.\n"
            "Apply **all three** thresholds simultaneously to narrow down to the most critical record:\n\n"
            "- **failed_login_count ≥ 8** — nine or more consecutive failures suggest a brute-force attempt\n"
            "- **device_trust_score < 15** — below 15 means an unrecognised, unmanaged device\n"
            "- **ip_risk_score > 90** — above 90 places the source in a known-bad IP range\n\n"
            "> **Verification tip:** After filtering, look at which candidates were cleared and why.\n"
            "> Do not decode anything until you can explain why each ruled-out record was legitimate."
        ),
        code(step2),
        md(
            "## Step 3 — Decode the embedded clue\n\n"
            "The suspicious transaction note contains a prefixed Base64 message.\n"
            "Strip the prefix (`ADMIN-RECOVERY:`) and decode the remainder to recover\n"
            "the final investigation clue."
        ),
        code(decode),
    ]


def generate_notebooks(config: dict[str, str]) -> tuple[Path, Path]:
    base = {"metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}, "language_info": {"name": "python", "version": "3"}}, "nbformat": 4, "nbformat_minor": 5}
    student = ROOT / "public" / "evidence" / "fraud_analysis.ipynb"
    solution = ROOT / "facilitator" / "fraud_analysis_completed.ipynb"
    for path, completed in ((student, False), (solution, True)):
        document = dict(base)
        document["cells"] = notebook_cells(config, completed)
        path.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")
    return student, solution


def main() -> None:
    config = load_env(CONFIG_PATH)
    require(
        config,
        "IMAGE_FLAG", "IMAGE_CHARADE", "IMAGE_NEXT", "IMAGE_SOURCE", "IMAGE_OUTPUT",
        "DNS_FLAG", "DNS_CHARADE", "DNS_NEXT", "DNS_DOMAIN",
        "WEBSITE_FLAG", "WEBSITE_CHARADE", "WEBSITE_NEXT",
        "NOTEBOOK_FLAG", "NOTEBOOK_CHARADE", "NOTEBOOK_NEXT",
        "CHAT_FLAG", "CHAT_SECRET_NOTE", "CHAT_NEXT",
        "ADMIN_USERNAME", "FINAL_PASSWORD", "GENERATION_SEED",
    )
    rng = random.Random(config["GENERATION_SEED"])
    outputs = [
        generate_image(config),
        generate_dns(config, rng),
        generate_website(config),
        generate_chat_secret(config),
        generate_admin_credentials(config),
        *generate_notebooks(config),
    ]
    print("Generated Citadelle challenge assets:")
    for output in outputs:
        print(f"  - {output.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
